#!/bin/bash

# Exit on errors, print commands, ignore unset variables
set -ex +u

# Do additional tasks that are common across all images, 
# but not suitable for inclusion in install.sh
echo "Running install_common.sh"

# Limit the maximum length of systemd-journald logs
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/60-limit-log-size.conf <<EOF
# Added by Photonvision to keep the logs to a reasonable size
[Journal]
SystemMaxUse=100M
EOF

# Create user photon:vision login
echo "creating photon user"
useradd photon -m -b /home -s /bin/bash
usermod -a -G sudo photon
echo 'photon ALL=(ALL) NOPASSWD: ALL' | tee -a /etc/sudoers.d/010_photon-nopasswd >/dev/null
chmod 0440 /etc/sudoers.d/010_photon-nopasswd

echo "photon:vision" | chpasswd

# Add a helpful message to the logon screen
# ASCII Art generated by: https://www.asciiart.eu/image-to-ascii
cp -f ./files/issue.txt /etc/issue
cp -f /etc/issue /etc/issue.net
echo "Banner /etc/issue.net" > /etc/ssh/sshd_config.d/90_PhotonVisionBanner.conf

# Add photon version file
mkdir -p /opt/photonvision/

# Keep this for legacy purposes
# DEPRECATED: removal in 2027
echo "${GITHUB_REF_NAME};${image_name}" > /opt/photonvision/image-version

cp -f ./image-version.json /opt/photonvision/image-version.json
